### ISSUE TITLE
Unable to load list of branches and unable to switch to other branches

### ISSUE THREAD

**Issue by kedziorm** [pockethub/PocketHub#1040]
When I open private repository (I have write access in this repository), I am unable to switch branch.

Regardless of being in "code" or "commits" tab, when I tap on branch name, I always see information that loading branch lists resulted in an error.
It seems that this issue doesn't exists on public repositories.

**Comment by Meisolsson** [comment]
Do you have a lot of branches and tags? Just tested on a private repository and had no problems.

**Comment by kedziorm** [comment]
15 active branches (26 total).
Maybe this is related with old Android version (4.3)?

![Error when switching branch in code tab](https://github.com/kedziorm/testowe/blob/master/InCode.png)
![Error when switching branch in commits tab](https://github.com/kedziorm/testowe/blob/master/InCommits.png)

**Comment by piaseckim** [comment]
I also have access to repository mentioned by @kedziorm and it ends up with the same error (Android 5.1).

**Comment by kedziorm** [comment]
@Meisolsson @piaseckim Issue exists on Android 6.0 phone as well.

I thought that it is caused by "_" and "-" characters in branches names and tags, so I created repository with such characters: https://github.com/kedziorm/This_is_just_for_testing
but it seems this is not the case.

I've tried to debug PocketHub (please note, I have zero experience in debugging Android soft), so I downloaded Android Studio.

Unfortunately, even though I set in _gradle-wrapper.properties_, pockethub_github_client and two other settings, each time when I try to run, I see:

> You won't be able to login, because the oauth client or secret isn't set
> Read the README.md: https://github.com/pockethub/PocketHub#setup-environment

and it is correct - I am unable to authenticate and as a result I am unable to debug.

**Comment by larsgrefer** [comment]
@kedziorm The properties doesn't belong into the `gradle-wrapper.properties` file.

See here for the possible ways of setting the properties: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_properties_and_system_properties

I suggest to use the `grade.properties` file in your *gradle user home directory*

**Comment by kedziorm** [comment]
Okay, now I'm receiving different error (when trying to log in in Pocket Hub):

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.github.pockethub.android, PID: 3182
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=https://github.com/... }} to activity {com.github.pockethub.android/com.github.pockethub.android.accounts.LoginActivity}: java.lang.IllegalStateException: Missing required properties: code
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.IllegalStateException: Missing required properties: code
                      at com.meisolsson.githubsdk.model.request.$$AutoValue_RequestToken$Builder.build($$AutoValue_RequestToken.java:147)
                      at com.github.pockethub.android.accounts.LoginActivity.onUserLoggedIn(LoginActivity.java:143)
                      at com.github.pockethub.android.accounts.LoginActivity.onActivityResult(LoginActivity.java:210)
                      at android.app.Activity.dispatchActivityResult(Activity.java:6428)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
                      at android.app.ActivityThread.-wrap16(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```
I guess that those values are caused by incorrect Callback URL or other settings that I provided when registering new app.

Could you be so kind and prepare sample configuration in the readme file for this repo, please?
To be honest, I'm really confused why I need to register application to debug Android app and I have completely no idea how callback URL should look like. You're saying that it should be `your_schema://whatever_you_want`, but what is your_schema?

**Comment by Meisolsson** [comment]
This seems to be solved.

**Comment by kedziorm** [comment]
@Meisolsson, @piaseckim This issue still exists on my phone although currently I use Android 6.0 phone. Will it be possible to re-open it? How can I help to reproduce it?

**Comment by Meisolsson** [comment]
@kedziorm Are you using the version on the Play Store or the version in master?

**Comment by kedziorm** [comment]
@Meisolsson I use version from the Play Store.

**Comment by Meisolsson** [comment]
I think we fixed it in the master version here but I've haven't had the time to upload the current version.
