### ISSUE TITLE
error when link from chrome

### ISSUE THREAD

**Issue by twixi** [pockethub/PocketHub#1163]
miui 9, 6 android

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.github.pockethub.android.ui.repo.RepositoryViewActivity.onPrepareOptionsMenu(RepositoryViewActivity.java:141)
	at android.app.Activity.onPreparePanel(Activity.java:2966)
	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:535)
	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:523)
	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:103)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:362)
	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:103)
	at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by Meisolsson** [comment]
This issue has been resolved, but not updated on the Play Store. Are you running the Play Store version?

**Comment by twixi** [comment]
GP VERSION

**Comment by Meisolsson** [comment]
Alright, there will be a fix out soon. Just have some other issues to sort out before that.
