### ISSUE TITLE
App fails to start on API < 21

### ISSUE THREAD

**Issue by larsgrefer** [pockethub/PocketHub#928]
The App fails to start on API < 21 on inflating the linear layout in the header view of the NavigationDrawer because `<dimen name="toolbar_top_padding">24dp</dimen>` is only specified for API >= 21:

```
10-12 20:42:51.289 6998-6998/com.github.pockethub W/ResourceType: Failure getting entry for 0x7f090019 (t=8 e=25) in package 0 (error -75)
10-12 20:42:51.299 6998-6998/com.github.pockethub W/ResourceType: Failure getting entry for 0x7f090019 (t=8 e=25) in package 0 (error -75)
```
...
```
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:  Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.View.<init>(View.java:2821)
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.ViewGroup.<init>(ViewGroup.java:405)
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.widget.LinearLayout.<init>(LinearLayout.java:174)
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.widget.LinearLayout.<init>(LinearLayout.java:170)
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:586) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:207) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:246) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:168) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.support.design.widget.NavigationView.<init>(NavigationView.java:92) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at java.lang.reflect.Constructor.constructNative(Native Method) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:586) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:255) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at com.github.pockethub.ui.MainActivity.onCreate(MainActivity.java:90) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:4538) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2161) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2240) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:139) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:156) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4977) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
10-12 20:42:51.389 6998-6998/com.github.pockethub E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by Meisolsson** [comment]
Well you did removed it earlier (https://github.com/pockethub/PocketHub/commit/e907cc38debfa67d8038100a399d81812c58120c). I'll re-add it.

**Comment by larsgrefer** [comment]
Oops :sweat_smile:
