### ISSUE TITLE
App will not login after enabling 2FA with U2F

### ISSUE THREAD

**Issue by rudolph75** [pockethub/PocketHub#950]
App was previously working with just username and password.  Enabled 2FA with Google Authentication App, then enabled three U2F keys for the account.  When opening app again, it backs out to the login screen.  When at the login screen, tried to login with Username, Password, & 2FA code.  It then sends me back to login screen with a Toast saying "Please enter a valid login & password".   Have tried uninstalling and reinstalling.

Stack trace provided:

```java
11-14 15:22:39.486  11376-11376/? D/TwoFactorAuthActivity﹕ Exception requesting handling two-factor authentication
    org.eclipse.egit.github.core.client.RequestException: Requires authentication (401)
            at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
            at com.github.mobile.accounts.TwoFactorAuthClient.get(TwoFactorAuthClient.java:88)
            at org.eclipse.egit.github.core.service.UserService.getUser(UserService.java:95)
            at com.github.mobile.accounts.TwoFactorAuthActivity$5.call(TwoFactorAuthActivity.java:229)
            at com.github.mobile.accounts.TwoFactorAuthActivity$5.call(TwoFactorAuthActivity.java:215)
            at roboguice.util.SafeAsyncTask$Task.doCall(SafeAsyncTask.java:204)
            at roboguice.util.SafeAsyncTask$Task.call(SafeAsyncTask.java:170)
            at roboguice.util.SafeAsyncTask$Task.call(SafeAsyncTask.java:158)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
            at dalvik.system.VMStack.getThreadStackTrace(Native Method)
            at java.lang.Thread.getStackTrace(Thread.java:580)
            at roboguice.util.SafeAsyncTask.execute(SafeAsyncTask.java:90)
            at com.github.mobile.accounts.TwoFactorAuthActivity.handleLogin(TwoFactorAuthActivity.java:260)
            at com.github.mobile.accounts.TwoFactorAuthActivity.onOptionsItemSelected(TwoFactorAuthActivity.java:185)
            at com.actionbarsherlock.app.SherlockActivity.onMenuItemSelected(SherlockActivity.java:197)
            at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:600)
            at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
            at com.actionbarsherlock.app.SherlockActivity.onOptionsItemSelected(SherlockActivity.java:148)
            at android.app.Activity.onMenuItemSelected(Activity.java:3024)
            at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1208)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
            at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:611)
            at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:180)
            at android.view.View.performClick(View.java:5197)
            at android.view.View$PerformClick.run(View.java:20926)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by hzsweers** [comment]
Are you using the build from master or the last version that was in the
play store?

**Comment by rudolph75** [comment]
This is from the latest Play store build. Version 1.9.0

**Comment by hzsweers** [comment]
We no longer support those builds. That said, that was using an old version of github's authentication that no longer supports 2FA. This was fixed in master a long time ago, you'll have to build this app and use this instead. See the README if you have any further questions.
