### ISSUE TITLE
Crash on Android 4.4.4 Vector WelcomeActivity

### ISSUE THREAD

**Issue by ceduliocezar** [pockethub/PocketHub#995]
App crash right after started on android 4.4.4

Stack:

   		Process: com.github.pockethub, PID: 14221
		java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.pockethub/com.github.pockethub.ui.WelcomeActivity}: android.view.InflateException: Binary XML file line #92: Error inflating class ImageButton
		  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
		  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
		  at android.app.ActivityThread.access$800(ActivityThread.java:139)
		  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
		  at android.os.Handler.dispatchMessage(Handler.java:102)
		  at android.os.Looper.loop(Looper.java:136)
		  at android.app.ActivityThread.main(ActivityThread.java:5086)
		  at java.lang.reflect.Method.invokeNative(Native Method)
		  at java.lang.reflect.Method.invoke(Method.java:515)
		  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
		  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
		  at dalvik.system.NativeStart.main(Native Method)
		Caused by: android.view.InflateException: Binary XML file line #92: Error inflating class ImageButton
		  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
		  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
		  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
		  at com.github.pockethub.ui.DotPagerActivity.onCreate(DotPagerActivity.java:73)
		  at com.github.pockethub.ui.WelcomeActivity.onCreate(WelcomeActivity.java:59)
		  at android.app.Activity.performCreate(Activity.java:5248)
		  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
		  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
		  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
		  at android.app.ActivityThread.access$800(ActivityThread.java:139) 
		  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) 
		  at android.os.Handler.dispatchMessage(Handler.java:102) 
		  at android.os.Looper.loop(Looper.java:136) 
		  at android.app.ActivityThread.main(ActivityThread.java:5086) 
		  at java.lang.reflect.Method.invokeNative(Native Method) 
		  at java.lang.reflect.Method.invoke(Method.java:515) 
		  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
		  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
		  at dalvik.system.NativeStart.main(Native Method) 
		Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_right.xml from drawable resource ID #0x7f020058
		  at android.content.res.Resources.loadDrawable(Resources.java:2099)
		  at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
		  at android.widget.ImageView.<init>(ImageView.java:139)
		  at android.widget.ImageButton.<init>(ImageButton.java:87)
		  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57)
		  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53)
		  at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118)
		  at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963)
		  at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022)
		  at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
		  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
		  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
		  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
		  at com.github.pockethub.ui.DotPagerActivity.onCreate(DotPagerActivity.java:73) 
		  at com.github.pockethub.ui.WelcomeActivity.onCreate(WelcomeActivity.java:59) 
		  at android.app.Activity.performCreate(Activity.java:5248) 
		  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
		  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162) 
		  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
		  at android.app.ActivityThread.access$800(ActivityThread.java:139) 
		  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) 
		  at android.os.Handler.dispatchMessage(Handler.java:102) 
		  at android.os.Looper.loop(Looper.java:136) 
		  at android.app.ActivityThread.main(ActivityThread.java:5086) 
		  at java.lang.reflect.Method.invokeNative(Native Method) 
		  at java.lang.reflect.Method.invoke(Method.java:515) 
		  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
		  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
		  at dalvik.system.NativeStart.main(Native Method) 
		Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
		  at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
		  at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
		  at android.content.res.Resources.loadDrawable(Resources.java:2095)
		  at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
		  at android.widget.ImageView.<init>(ImageView.java:139) 
		  at android.widget.ImageButton.<init>(ImageButton.java:87) 
		  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57) 
		  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53) 
		  at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118) 
		  at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963) 
		  at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022) 
		  at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44) 
		  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684) 
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
		  at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
		  at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
		  at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
		  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
		  at com.github.pockethub.ui.DotPagerActivity.onCreate(DotPagerActivity.java:73) 
		  at com.github.pockethub.ui.WelcomeActivity.onCreate(WelcomeActivity.java:59) 
		  at android.app.Activity.performCreate(Activity.java:5248) 
		  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110) 
		  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162) 
		  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
		  at android.app.ActivityThread.access$800(ActivityThread.java:139) 
		  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) 
		  at android.os.Handler.dispatchMessage(Handler.java:102) 
		  at android.os.Looper.loop(Looper.java:136) 
		  at android.app.ActivityThread.main(ActivityThread.java:5086) 
		  at java.lang.reflect.Method.invokeNative(Native Method) 
		  at java.lang.reflect.Method.invoke(Method.java:515) 
		  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
		  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
		  at dalvik.system.NativeStart.main(Native Method)

**Comment by ahangchen** [comment]
@ceduliocezar You need to change the 
ImageButton's 
```xml
android:src="@drawable/ic_arrow_right
```
attribute to  
```xml
app:srcCompat="@drawable/ic_arrow_right"
```
when you use vector on devices below api 21.

**Comment by hzsweers** [comment]
@ahangchen that's not correct because the gradle plugin should generate those PNG assets from the vector in the current repo state. Something else is going on

**Comment by ahangchen** [comment]
@hzsweers I didn't change the gradle files. I just modify this attribute and fix it... 
As mentioned in this [blog](http://android-developers.blogspot.com/2016/02/android-support-library-232.html), I think app:srcCompat is the recommended way. 
By the way, this discussion may be helpful 
http://stackoverflow.com/questions/35622438/update-android-support-library-to-23-2-0-cause-error-xmlpullparserexception-bin

**Comment by hzsweers** [comment]
Ah shoot, I forgot someone slipped in that bump in a PR awhile back. Sorry, my bad.

**Comment by EhsanHasin** [comment]
thank you @ahangchen
