### ISSUE TITLE
Crash on 4.2.2 because error inflating ImageButton which contains vector resource

### ISSUE THREAD

**Issue by markzhai** [pockethub/PocketHub#998]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.pockethub/com.github.pockethub.ui.WelcomeActivity}: android.view.InflateException: Binary XML file line #92: Error inflating class ImageButton
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.view.InflateException: Binary XML file line #92: Error inflating class ImageButton
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                                          at com.github.pockethub.ui.DotPagerActivity.onCreate(DotPagerActivity.java:73)
                                                                          at com.github.pockethub.ui.WelcomeActivity.onCreate(WelcomeActivity.java:59)
                                                                          at android.app.Activity.performCreate(Activity.java:5104)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_right.xml from drawable resource ID #0x7f02005a
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:1953)
                                                                          at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                                          at android.widget.ImageView.<init>(ImageView.java:120)
                                                                          at android.widget.ImageButton.<init>(ImageButton.java:87)
                                                                          at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57)
                                                                          at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53)
                                                                          at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022)
                                                                          at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                          at com.github.pockethub.ui.DotPagerActivity.onCreate(DotPagerActivity.java:73) 
                                                                          at com.github.pockethub.ui.WelcomeActivity.onCreate(WelcomeActivity.java:59) 
                                                                          at android.app.Activity.performCreate(Activity.java:5104) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                          at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
                                                                          at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
                                                                          at android.content.res.Resources.loadDrawable(Resources.java:1950)
                                                                          at android.content.res.TypedArray.getDrawable(TypedArray.java:601) 
                                                                          at android.widget.ImageView.<init>(ImageView.java:120) 
                                                                          at android.widget.ImageButton.<init>(ImageButton.java:87) 
                                                                          at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57) 
                                                                          at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:53) 
                                                                          at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:963) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1022) 
                                                                          at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                          at com.github.pockethub.ui.DotPagerActivity.onCreate(DotPagerActivity.java:73) 
                                                                          at com.github.pockethub.ui.WelcomeActivity.onCreate(WelcomeActivity.java:59) 
                                                                          at android.app.Activity.performCreate(Activity.java:5104) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                          at android.os.Looper.loop(Looper.java:137) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by markzhai** [comment]
Using gradle tools version 2.0.0

**Comment by Meisolsson** [comment]
This is identical to #995, closing this

**Comment by Sufi313** [comment]
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                             at com.taggroup.www.darzeeco.CustomerAct.CartAdapter.onCreateViewHolder(CartAdapter.java:42)
                                                                             at com.taggroup.www.darzeeco.CustomerAct.CartAdapter.onCreateViewHolder(CartAdapter.java:27)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                             at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at android.widget.ScrollView.onMeasure(ScrollView.java:326)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                         	at android



The same error in my emulator  make this app in oreo minimum skd 19 but multidex enabled but run error show

**Comment by Sufi313** [comment]
application here [https://github.com/sufi313/sufwan](url)
