### ISSUE TITLE
NullPointerException in IssuesViewActivity

### ISSUE THREAD

**Issue by markzhai** [pockethub/PocketHub#999]
Met this when open a issue, client shows a white page, I wait and wait, still white, clicked back button and then it crashed.

From the code, it seems to caused because when click the button, the `pager` has not been initialized as response is not back yet (configurePager is called when response back).

```java
    private void configurePager() {
        int initialPosition = getIntExtra(EXTRA_POSITION);
        pager = finder.find(R.id.vp_pages);

        if (repo != null)
            adapter = new IssuesPagerAdapter(this, repo, issueNumbers, isCollaborator, isOwner);
        else
            adapter = new IssuesPagerAdapter(this, repoIds, issueNumbers, store, isCollaborator, isOwner);
        pager.setAdapter(adapter);

        pager.setOnPageChangeListener(this);
        pager.scheduleSetItem(initialPosition, this);
        onPageSelected(initialPosition);
    }
```

```log
04-15 11:06:36.328 17099-17099/com.github.pockethub E/AndroidRuntime: FATAL EXCEPTION: main
  java.lang.NullPointerException
      at com.github.pockethub.ui.issue.IssuesViewActivity.onOptionsItemSelected(IssuesViewActivity.java:322)
      at android.app.Activity.onMenuItemSelected(Activity.java:2548)
      at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:404)
      at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:167)
      at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
      at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
      at android.support.v7.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:192)
      at android.view.View.performClick(View.java:4204)
      at android.view.View$PerformClick.run(View.java:17355)
      at android.os.Handler.handleCallback(Handler.java:725)
      at android.os.Handler.dispatchMessage(Handler.java:92)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:5041)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
      at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Meisolsson** [comment]
This should have been resolved by #1004
